name: appfotajer
description: "تطبيق توصيل طلبات"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # الإشعارات والاتصالات
  flutter_local_notifications: ^19.4.0  # تم تحديث الإصدار
  firebase_core: ^4.0.0  # تم تحديث الإصدار
  firebase_messaging: ^16.0.0  # تم تحديث الإصدار
  
  # إدارة الحالة
  provider: ^6.1.1  # تم تحديث الإصدار
  flutter_bloc: ^9.1.1  # تم تحديث الإصدار
  
  # الوسائط
  image_picker: ^1.0.4
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.3.0
  
  # التخزين والأمان
  appwrite: ^17.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # الموقع والخرائط
  geolocator: ^14.0.2  # تم تحديث الإصدار
  google_maps_flutter: ^2.2.3
  
  # التوطين والتنسيق
  intl: ^0.20.2  # تم تحديث الإصدار
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.0
  
  # أدوات مساعدة
  fluttertoast: ^8.2.2
  uuid: ^4.5.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
 # أضفت مجلد الأيقونات إن وجد